spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    initialization-mode: always
    schema: "classpath:/schema.sql"
  flyway:
    enabled: true
    baselineOnMigrate: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "${GITHUB_OAUTH_CLIENT_ID}"
            clientSecret: "${GITHUB_OAUTH_SECRET}"
          google:
            client-id: "${GOOGLE_OAUTH_CLIENT_ID}"
            client-secret: "${GOOGLE_OAUTH_SECRET}"
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
  error:
    include-message: always
maps:
  apiKey: "${MAPS_API_KEY}"
