spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    initialization-mode: always
    schema: "classpath:/schema.sql"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 53ff8705e4be94320cbc
            clientSecret: a8a101f8419e27a92dd8f84a5dcf25593a2dadae
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
  error:
    include-message: always
maps:
  apiKey: "AIzaSyDAyURyzuAi38Am-nkzYCAao52ZhEWDu10"
