INSERT INTO pokemon (name) VALUES ('Bulbasaur');
INSERT INTO pokemon (name) VALUES ('Ivysaur');
INSERT INTO pokemon (name) VALUES ('Venusaur');
INSERT INTO pokemon (name) VALUES ('Charmander');
INSERT INTO pokemon (name) VALUES ('Charmeleon');
INSERT INTO pokemon (name) VALUES ('Charizard');
INSERT INTO pokemon (name) VALUES ('Squirtle');
INSERT INTO pokemon (name) VALUES ('Wartortle');
INSERT INTO pokemon (name) VALUES ('Blastoise');
INSERT INTO pokemon (name) VALUES ('Caterpie');
INSERT INTO pokemon (name) VALUES ('Metapod');
INSERT INTO pokemon (name) VALUES ('Butterfree');
INSERT INTO pokemon (name) VALUES ('Weedle');
INSERT INTO pokemon (name) VALUES ('Kakuna');
INSERT INTO pokemon (name) VALUES ('Beedrill');
INSERT INTO pokemon (name) VALUES ('Pidgey');
INSERT INTO pokemon (name) VALUES ('Pidgeotto');
INSERT INTO pokemon (name) VALUES ('Pidgeot');
INSERT INTO pokemon (name) VALUES ('Rattata');
INSERT INTO pokemon (name) VALUES ('Raticate');
INSERT INTO pokemon (name) VALUES ('Spearow');
INSERT INTO pokemon (name) VALUES ('Fearow');
INSERT INTO pokemon (name) VALUES ('Ekans');
INSERT INTO pokemon (name) VALUES ('Arbok');
INSERT INTO pokemon (name) VALUES ('Pikachu');
INSERT INTO pokemon (name) VALUES ('Raichu');
INSERT INTO pokemon (name) VALUES ('Sandshrew');
INSERT INTO pokemon (name) VALUES ('Sandslash');
INSERT INTO pokemon (name) VALUES ('Nidoran♀');
INSERT INTO pokemon (name) VALUES ('Nidorina');
INSERT INTO pokemon (name) VALUES ('Nidoqueen');
INSERT INTO pokemon (name) VALUES ('Nidoran♂');
INSERT INTO pokemon (name) VALUES ('Nidorino');
INSERT INTO pokemon (name) VALUES ('Nidoking');
INSERT INTO pokemon (name) VALUES ('Clefairy');
INSERT INTO pokemon (name) VALUES ('Clefable');
INSERT INTO pokemon (name) VALUES ('Vulpix');
INSERT INTO pokemon (name) VALUES ('Ninetales');
INSERT INTO pokemon (name) VALUES ('Jigglypuff');
INSERT INTO pokemon (name) VALUES ('Wigglytuff');
INSERT INTO pokemon (name) VALUES ('Zubat');
INSERT INTO pokemon (name) VALUES ('Golbat');
INSERT INTO pokemon (name) VALUES ('Oddish');
INSERT INTO pokemon (name) VALUES ('Gloom');
INSERT INTO pokemon (name) VALUES ('Vileplume');
INSERT INTO pokemon (name) VALUES ('Paras');
INSERT INTO pokemon (name) VALUES ('Parasect');
INSERT INTO pokemon (name) VALUES ('Venonat');
INSERT INTO pokemon (name) VALUES ('Venomoth');
INSERT INTO pokemon (name) VALUES ('Diglett');
INSERT INTO pokemon (name) VALUES ('Dugtrio');
INSERT INTO pokemon (name) VALUES ('Meowth');
INSERT INTO pokemon (name) VALUES ('Persian');
INSERT INTO pokemon (name) VALUES ('Psyduck');
INSERT INTO pokemon (name) VALUES ('Golduck');
INSERT INTO pokemon (name) VALUES ('Mankey');
INSERT INTO pokemon (name) VALUES ('Primeape');
INSERT INTO pokemon (name) VALUES ('Growlithe');
INSERT INTO pokemon (name) VALUES ('Arcanine');
INSERT INTO pokemon (name) VALUES ('Poliwag');
INSERT INTO pokemon (name) VALUES ('Poliwhirl');
INSERT INTO pokemon (name) VALUES ('Poliwrath');
INSERT INTO pokemon (name) VALUES ('Abra');
INSERT INTO pokemon (name) VALUES ('Kadabra');
INSERT INTO pokemon (name) VALUES ('Alakazam');
INSERT INTO pokemon (name) VALUES ('Machop');
INSERT INTO pokemon (name) VALUES ('Machoke');
INSERT INTO pokemon (name) VALUES ('Machamp');
INSERT INTO pokemon (name) VALUES ('Bellsprout');
INSERT INTO pokemon (name) VALUES ('Weepinbell');
INSERT INTO pokemon (name) VALUES ('Victreebel');
INSERT INTO pokemon (name) VALUES ('Tentacool');
INSERT INTO pokemon (name) VALUES ('Tentacruel');
INSERT INTO pokemon (name) VALUES ('Geodude');
INSERT INTO pokemon (name) VALUES ('Graveler');
INSERT INTO pokemon (name) VALUES ('Golem');
INSERT INTO pokemon (name) VALUES ('Ponyta');
INSERT INTO pokemon (name) VALUES ('Rapidash');
INSERT INTO pokemon (name) VALUES ('Slowpoke');
INSERT INTO pokemon (name) VALUES ('Slowbro');
INSERT INTO pokemon (name) VALUES ('Magnemite');
INSERT INTO pokemon (name) VALUES ('Magneton');
INSERT INTO pokemon (name) VALUES ('Farfetch');
INSERT INTO pokemon (name) VALUES ('Doduo');
INSERT INTO pokemon (name) VALUES ('Dodrio');
INSERT INTO pokemon (name) VALUES ('Seel');
INSERT INTO pokemon (name) VALUES ('Dewgong');
INSERT INTO pokemon (name) VALUES ('Grimer');
INSERT INTO pokemon (name) VALUES ('Muk');
INSERT INTO pokemon (name) VALUES ('Shellder');
INSERT INTO pokemon (name) VALUES ('Cloyster');
INSERT INTO pokemon (name) VALUES ('Gastly');
INSERT INTO pokemon (name) VALUES ('Haunter');
INSERT INTO pokemon (name) VALUES ('Gengar');
INSERT INTO pokemon (name) VALUES ('Onix');
INSERT INTO pokemon (name) VALUES ('Drowzee');
INSERT INTO pokemon (name) VALUES ('Hypno');
INSERT INTO pokemon (name) VALUES ('Krabby');
INSERT INTO pokemon (name) VALUES ('Kingler');
INSERT INTO pokemon (name) VALUES ('Voltorb');
INSERT INTO pokemon (name) VALUES ('Electrode');
INSERT INTO pokemon (name) VALUES ('Exeggcute');
INSERT INTO pokemon (name) VALUES ('Exeggutor');
INSERT INTO pokemon (name) VALUES ('Cubone');
INSERT INTO pokemon (name) VALUES ('Marowak');
INSERT INTO pokemon (name) VALUES ('Hitmonlee');
INSERT INTO pokemon (name) VALUES ('Hitmonchan');
INSERT INTO pokemon (name) VALUES ('Lickitung');
INSERT INTO pokemon (name) VALUES ('Koffing');
INSERT INTO pokemon (name) VALUES ('Weezing');
INSERT INTO pokemon (name) VALUES ('Rhyhorn');
INSERT INTO pokemon (name) VALUES ('Rhydon');
INSERT INTO pokemon (name) VALUES ('Chansey');
INSERT INTO pokemon (name) VALUES ('Tangela');
INSERT INTO pokemon (name) VALUES ('Kangaskhan');
INSERT INTO pokemon (name) VALUES ('Horsea');
INSERT INTO pokemon (name) VALUES ('Seadra');
INSERT INTO pokemon (name) VALUES ('Goldeen');
INSERT INTO pokemon (name) VALUES ('Seaking');
INSERT INTO pokemon (name) VALUES ('Staryu');
INSERT INTO pokemon (name) VALUES ('Starmie');
INSERT INTO pokemon (name) VALUES ('Mr. Mime');
INSERT INTO pokemon (name) VALUES ('Scyther');
INSERT INTO pokemon (name) VALUES ('Jynx');
INSERT INTO pokemon (name) VALUES ('Electabuzz');
INSERT INTO pokemon (name) VALUES ('Magmar');
INSERT INTO pokemon (name) VALUES ('Pinsir');
INSERT INTO pokemon (name) VALUES ('Tauros');
INSERT INTO pokemon (name) VALUES ('Magikarp');
INSERT INTO pokemon (name) VALUES ('Gyarados');
INSERT INTO pokemon (name) VALUES ('Lapras');
INSERT INTO pokemon (name) VALUES ('Ditto');
INSERT INTO pokemon (name) VALUES ('Eevee');
INSERT INTO pokemon (name) VALUES ('Vaporeon');
INSERT INTO pokemon (name) VALUES ('Jolteon');
INSERT INTO pokemon (name) VALUES ('Flareon');
INSERT INTO pokemon (name) VALUES ('Porygon');
INSERT INTO pokemon (name) VALUES ('Omanyte');
INSERT INTO pokemon (name) VALUES ('Omastar');
INSERT INTO pokemon (name) VALUES ('Kabuto');
INSERT INTO pokemon (name) VALUES ('Kabutops');
INSERT INTO pokemon (name) VALUES ('Aerodactyl');
INSERT INTO pokemon (name) VALUES ('Snorlax');
INSERT INTO pokemon (name) VALUES ('Articuno');
INSERT INTO pokemon (name) VALUES ('Zapdos');
INSERT INTO pokemon (name) VALUES ('Moltres');
INSERT INTO pokemon (name) VALUES ('Dratini');
INSERT INTO pokemon (name) VALUES ('Dragonair');
INSERT INTO pokemon (name) VALUES ('Dragonite');
INSERT INTO pokemon (name) VALUES ('Mewtwo');
INSERT INTO pokemon (name) VALUES ('Mew');

INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',10,1);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,2);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,3);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',10,4);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,5);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,6);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',10,7);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,8);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,9);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',80,10);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',40,11);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',10,12);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',80,13);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',40,14);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',10,15);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',60,16);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',40,16);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',25,17);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',10,17);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',5,18);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',1,18);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',80,19);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',30,20);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',70,21);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',10,22);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',20,23);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',40,23);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',1,24);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',5,24);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',10,25);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',1,26);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SAND',80,27);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',50,27);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SAND',10,28);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',10,28);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',70,29);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',30,30);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',5,31);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',70,32);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',30,33);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',5,34);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',30,35);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',5,36);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',30,37);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',1,38);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',30,39);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',5,40);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',80,41);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',20,42);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',80,43);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',30,44);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',5,45);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',60,46);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',5,47);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',60,48);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',5,49);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CANYON',100,50);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',40,50);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CANYON',40,51);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',5,51);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',60,52);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',10,53);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',50,54);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',50,54);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',5,55);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',10,55);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',50,56);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',50,56);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',5,57);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',5,57);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POLICE',40,58);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POLICE',1,59);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',60,60);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',10,61);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',20,61);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',1,62);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',5,62);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',60,63);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',5,64);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',1,65);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GYM',80,66);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GYM',20,67);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GYM',5,68);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',80,69);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',30,70);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',5,71);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',80,72);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',10,73);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',80,74);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',20,75);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',5,76);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FARM',60,77);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FARM',5,78);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',60,79);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',5,80);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',70,81);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ROAD',40,81);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',10,82);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ROAD',5,82);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRASS',20,83);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',70,84);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',10,85);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',40,86);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',10,86);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',5,87);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',1,87);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CITY',70,88);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CITY',10,89);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',60,90);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',5,91);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRAVEYARD',100,92);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRAVEYARD',20,93);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRAVEYARD',1,94);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MOUNTAIN',10,95);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',40,96);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',5,97);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',40,98);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',80,98);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',5,99);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',5,99);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',70,100);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',10,101);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',50,102);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',10,103);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRAVEYARD',50,104);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GRAVEYARD',5,105);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GYM',10,106);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GYM',10,107);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',40,108);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CITY',80,109);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('CITY',10,110);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',40,111);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',5,112);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('HOSPITAL',20,113);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',30,114);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',20,115);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',80,116);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',5,117);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',40,118);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',30,118);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',10,119);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',30,119);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',30,120);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',30,120);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',2,121);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',2,121);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',20,122);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',10,123);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',20,123);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',10,124);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POWER',10,125);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ZOO',10,126);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('GARDEN',10,127);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FOREST',20,127);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('FARM',60,128);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('POND',80,129);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SHORE',80,129);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('LAKE',5,130);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',10,130);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('OCEAN',10,131);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',1,132);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('URBAN',10,133);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,134);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,135);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('NONE',0,136);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('SCHOOL',5,137);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MUSEUM',80,138);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MUSEUM',10,139);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MUSEUM',80,140);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MUSEUM',10,141);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('MUSEUM',5,142);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ROAD',3,143);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.01,144);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.01,145);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.01,146);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',10,147);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('BEACH',1,148);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.1,149);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.01,150);
INSERT INTO habitats (habitat_type, rarity, pokemon_id) VALUES ('ANY',0.01,151);
