ALTER TABLE habitats ALTER id TYPE BIGINT;
ALTER TABLE habitats ALTER pokedex_id TYPE BIGINT;

ALTER TABLE pokemon ALTER id TYPE BIGINT;
ALTER TABLE pokemon ALTER pokedex_id TYPE BIGINT;

ALTER TABLE spawns ALTER id TYPE BIGINT;
ALTER TABLE spawns ALTER pokemon_id TYPE BIGINT;

ALTER TABLE visited_locations ALTER id TYPE BIGINT;
